### ISSUE TITLE
All Home Buttons crash the game

### ISSUE THREAD

**Issue by Tohaker** [GazePlay/GazePlay#1036]
### To Replicate
1. Open any game.
2. Click on the gear menu.
3. Click the Home icon.
4. Game crashes.

### Stack Trace
```
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Event filter must not be null
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.validateEventFilter(EventHandlerManager.java:267)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.removeEventFilter(EventHandlerManager.java:128)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at javafx.scene.Node.removeEventFilter(Node.java:8752)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at net.gazeplay.ui.scenes.ingame.GameContext.pointersClear(GameContext.java:142)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at net.gazeplay.ui.scenes.ingame.GameContext.exitGame(GameContext.java:228)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at net.gazeplay.ui.scenes.ingame.GameContext.lambda$createHomeButtonInGameScreen$4(GameContext.java:217)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2020-01-19 17:25:18,604 ERROR java.lang.Throwable - 	at javafx.event.Event.fireEvent(Event.java:198)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3564)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at javafx.scene.Scene$ClickGenerator.access$8200(Scene.java:3492)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3860)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.glass.ui.View.notifyMouse(View.java:942)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
2020-01-19 17:25:18,605 ERROR java.lang.Throwable - 	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Root Cause
It appears that in `GameContext.java: line 125` the `pointerEvent` is not being assigned because video recording is set to false by default, and is never getting called. 

### Next actions
@kuhlkrein This seems to be your recent change, is it safe to put the `pointersClear` method behind the same `if (this.getConfiguration().isVideoRecordingEnabled())` check?

**Comment by schwabdidier** [comment]
replicated :(

**Comment by Tohaker** [comment]
This really could have been caught early with some tests

**Comment by kuhlkrein** [comment]
You're right, I'm really sorry for that.

**Comment by Tohaker** [comment]
Mistakes happen, lets be more proactive about testing this stuff from now on 😄

**Comment by schwabdidier** [comment]
Yes, it is also my fault, I wanted to release this PR fastly... Let's add some tests and procedures.

**Comment by schwabdidier** [comment]
ok, we where not able to release on GazePlay repo but only on @kuhlkrein branch. Feel free to modify, we will try to release etc. as soon as possible.

**Comment by Tohaker** [comment]
Appears to be fixed, so I'll close this.
