### ISSUE TITLE
GazeMediaPlayer can't read AVI videos

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#1178]
**Describe the bug**
AVI video are not played and it trigger the error:
`2020-05-07 14:49:03,329 ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" MediaException: MEDIA_UNSUPPORTED : Unrecognized file signature!
2020-05-07 14:49:03,329 ERROR java.lang.Throwable - 	at javafx.media/javafx.scene.media.Media.<init>(Media.java:411)
2020-05-07 14:49:03,330 ERROR java.lang.Throwable - 	at net.gazeplay.games.mediaPlayer.GazeMediaPlayer.lambda$handlerMedia$19(GazeMediaPlayer.java:583)
2020-05-07 14:49:03,330 ERROR java.lang.Throwable - 	at net.gazeplay.components.GazeIndicator$OnFinishIndicatorEvent.handle(GazeIndicator.java:116)
2020-05-07 14:49:03,330 ERROR java.lang.Throwable - 	at net.gazeplay.components.GazeIndicator$OnFinishIndicatorEvent.handle(GazeIndicator.java:99)
2020-05-07 14:49:03,330 ERROR java.lang.Throwable - 	at javafx.graphics/javafx.animation.Animation.finished(Animation.java:1131)
2020-05-07 14:49:03,330 ERROR java.lang.Throwable - 	at javafx.graphics/javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
2020-05-07 14:49:03,330 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
2020-05-07 14:49:03,331 ERROR java.lang.Throwable - 	at javafx.graphics/javafx.animation.Animation.doTimePulse(Animation.java:1101)
2020-05-07 14:49:03,331 ERROR java.lang.Throwable - 	at javafx.graphics/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
2020-05-07 14:49:03,331 ERROR java.lang.Throwable - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-05-07 14:49:03,331 ERROR java.lang.Throwable - 	at javafx.graphics/javafx.animation.Animation$1.timePulse(Animation.java:185)
2020-05-07 14:49:03,331 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
2020-05-07 14:49:03,331 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
2020-05-07 14:49:03,332 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:520)
2020-05-07 14:49:03,332 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:504)
2020-05-07 14:49:03,332 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:497)
2020-05-07 14:49:03,332 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
2020-05-07 14:49:03,332 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
2020-05-07 14:49:03,332 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
2020-05-07 14:49:03,333 ERROR java.lang.Throwable - 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
2020-05-07 14:49:03,333 ERROR java.lang.Throwable - 	at java.base/java.lang.Thread.run(Thread.java:834)`

**To Reproduce**
add any avi video to the mediaPlayer and try to play

**Additional context**
it is due to javaFX media format that is not containing AVI format:
https://docs.oracle.com/javafx/2/api/javafx/scene/media/package-summary.html

**Comment by Tohaker** [comment]
Might just be worth removing the `.avi` filter from the file selector dialog

**Comment by schwabdidier** [comment]
No, I checked, we can select without problem but then it doesn't work. Oddly AVI is not supported...

**Comment by Tohaker** [comment]
Well thats why you remove it from the filter, then you can't select it anymore

**Comment by schwabdidier** [comment]
I don't understand what you mean

**Comment by Tohaker** [comment]
Ah looking at the code it seems we don't check file extensions when selecting music

**Comment by schwabdidier** [comment]
Should we ?

**Comment by Tohaker** [comment]
It would help if we can't fix this AVI issue
