### ISSUE TITLE
GazePlay freeze after some games

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#451]
After some "big games" with lot of images such as biboules for example, then gazeplay can return an error 

```
2018-05-29 13:38:24,971 ERROR - Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: Java heap space
2018-05-29 13:38:24,972 ERROR - 	at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:76)
2018-05-29 13:38:24,972 ERROR - 	at java.awt.image.Raster.createInterleavedRaster(Raster.java:266)
2018-05-29 13:38:24,972 ERROR - 	at java.awt.image.BufferedImage.<init>(BufferedImage.java:391)
2018-05-29 13:38:24,972 ERROR - 	at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1250)
2018-05-29 13:38:24,972 ERROR - 	at org.tc33.jheatchart.HeatChart.saveToFile(HeatChart.java:1205)
2018-05-29 13:38:24,988 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveHeatMapAsPng(Stats.java:218)
2018-05-29 13:38:24,988 ERROR - 	at net.gazeplay.commons.utils.stats.Stats.saveStats(Stats.java:117)
2018-05-29 13:38:24,988 ERROR - 	at net.gazeplay.commons.utils.stats.ShootGamesStats.saveStats(ShootGamesStats.java:17)
2018-05-29 13:38:24,988 ERROR - 	at net.gazeplay.GameContext.lambda$5(GameContext.java:308)
2018-05-29 13:38:24,988 ERROR - 	at net.gazeplay.GameContext$$Lambda$372/387314601.run(Unknown Source)
2018-05-29 13:38:24,988 ERROR - 	at net.gazeplay.GameContext.homeButtonClicked(GameContext.java:317)
2018-05-29 13:38:24,988 ERROR - 	at net.gazeplay.GameContext.lambda$4(GameContext.java:288)
2018-05-29 13:38:24,988 ERROR - 	at net.gazeplay.GameContext$$Lambda$341/1766003811.handle(Unknown Source)
2018-05-29 13:38:24,988 ERROR - 	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
2018-05-29 13:38:24,988 ERROR - 	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
2018-05-29 13:38:24,989 ERROR - 	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
2018-05-29 13:38:24,990 ERROR - 	at javafx.event.Event.fireEvent(Event.java:198)
2018-05-29 13:38:24,990 ERROR - 	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
2018-05-29 13:38:24,990 ERROR - 	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
2018-05-29 13:38:24,990 ERROR - 	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
2018-05-29 13:38:24,990 ERROR - 	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
2018-05-29 13:38:24,990 ERROR - 	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
```

and stops to work

**Comment by YannRobert** [comment]
```-Xms256m -Xmx1g``` ?

**Comment by kuhlkrein** [comment]
Ohh it increases the heap space ??

**Comment by WaffleBuffer** [comment]
Maybe because of this ? : 
From addListener function in javafx.​beans.​value.​ObservableValue (any properties) : 
The ObservableValue stores a strong reference to the listener which will prevent the listener from being garbage collected and may result in a memory leak. It is recommended to either unregister a listener by calling removeListener after use or to use an instance of WeakChangeListener avoid this situation.
I didn't find any concrete proof but maybe there is the same problem for any EventHandler/EventFilter.
Maybe removing all listeners will fix part of the problem ?

**Comment by WaffleBuffer** [comment]
I also found that there is a WeakEventHandler class so the problem may also apply to EventHandler

**Comment by WaffleBuffer** [comment]
I found this thread which explain the problem we *might* have (because i'm still not sure if it's our case here): https://stackoverflow.com/questions/14558266/clean-javafx-property-listeners-and-bindings-memory-leaks

**Comment by kuhlkrein** [comment]
Well, I did not really solve the issue but I reduced a lot the resolutions of images of the games leading to this error. Now it should become really really rare. We noticed with @MelanieCarriere that Wack-A-Mole was working on her computer but not on mine because of this error, we reduced the size and now it seems to work fine. The new images will be available in my next PR.
