### ISSUE TITLE
exception on gribouille

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#685]
occured only once ,

On closing gribouille :

2019-04-02 09:55:46,533 ERROR - java.lang.IllegalStateException: Operation requires resource lock
2019-04-02 09:55:46,533 ERROR - 	at com.sun.prism.impl.ManagedResource.assertLocked(ManagedResource.java:96)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.prism.impl.BaseTexture.assertLocked(BaseTexture.java:267)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.prism.impl.ps.BaseShaderContext.setTexture(BaseShaderContext.java:688)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(BaseShaderContext.java:584)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(BaseShaderContext.java:500)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.prism.impl.BaseGraphics.drawTextureRaw(BaseGraphics.java:714)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.impl.prism.ps.PPSOneSamplerPeer.filterImpl(PPSOneSamplerPeer.java:117)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.impl.prism.ps.PPSEffectPeer.filter(PPSEffectPeer.java:54)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.LinearConvolveCoreEffect.filterImageDatas(LinearConvolveCoreEffect.java:85)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.LinearConvolveCoreEffect.filterImageDatas(LinearConvolveCoreEffect.java:41)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:195)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.Offset.filter(Offset.java:160)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.Merge.filter(Merge.java:148)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.DelegateEffect.filter(DelegateEffect.java:70)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.scenario.effect.impl.prism.PrEffectHelper.render(PrEffectHelper.java:166)
2019-04-02 09:55:46,533 ERROR - 	at com.sun.javafx.sg.prism.EffectFilter.render(EffectFilter.java:61)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.javafx.sg.prism.NGNode.renderEffect(NGNode.java:2365)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2050)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
2019-04-02 09:55:46,534 ERROR - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2019-04-02 09:55:46,534 ERROR - 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
2019-04-02 09:55:46,534 ERROR - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-04-02 09:55:46,534 ERROR - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
2019-04-02 09:55:46,534 ERROR - 	at java.lang.Thread.run(Thread.java:748)
2019-04-02 09:55:46,534 ERROR - java.lang.IllegalArgumentException: Register not found for: oinvarcradii
2019-04-02 09:55:46,534 ERROR - 	at com.sun.prism.d3d.D3DShader.getRegister(D3DShader.java:189)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.prism.d3d.D3DShader.setConstants(D3DShader.java:175)
2019-04-02 09:55:46,534 ERROR - 	at com.sun.prism.d3d.D3DShader.setConstant(D3DShader.java:152)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedPgram(BaseShaderGraphics.java:846)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedRect(BaseShaderGraphics.java:601)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.prism.impl.ps.BaseShaderGraphics.fillRoundRect(BaseShaderGraphics.java:1557)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectanglesDirectly(NGRegion.java:1120)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectangle(NGRegion.java:849)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(NGRegion.java:752)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:573)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NodeEffectInput.getImageDataForBoundedNode(NodeEffectInput.java:237)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NodeEffectInput.filter(NodeEffectInput.java:131)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:185)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.scenario.effect.Offset.filter(Offset.java:160)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.scenario.effect.Merge.filter(Merge.java:148)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.scenario.effect.DelegateEffect.filter(DelegateEffect.java:70)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.scenario.effect.impl.prism.PrEffectHelper.render(PrEffectHelper.java:166)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.EffectFilter.render(EffectFilter.java:61)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NGNode.renderEffect(NGNode.java:2365)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2050)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
2019-04-02 09:55:46,535 ERROR - 	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
2019-04-02 09:55:46,535 ERROR - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2019-04-02 09:55:46,535 ERROR - 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2019-04-02 09:55:46,536 ERROR - 	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
2019-04-02 09:55:46,536 ERROR - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-04-02 09:55:46,536 ERROR - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-04-02 09:55:46,536 ERROR - 	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
2019-04-02 09:55:46,536 ERROR - 	at java.lang.Thread.run(Thread.java:748)

**Comment by Tohaker** [comment]
Have you been able to replicate this since?
