### ISSUE TITLE
Another bug on macOS

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#960]
When I click on house from statistics page, I obtain that

```
2019-12-13 14:22:09,367 WARN  net.gazeplay.ui.GraphicalContext - Nodes not removed: 0
2019-12-13 14:22:09,394 DEBUG net.gazeplay.ui.GraphicalContext - Finished setup stage with the game scene
2019-12-13 14:22:09.397 java[65991:3612855] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
Exception in thread "AppKit Thread" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'homeMenuScreenFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:135)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1818)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1266)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:346)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:227)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1155)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:416)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1126)
	at net.gazeplay.GazePlay.onReturnToMenu(GazePlay.java:58)
	at net.gazeplay.commons.utils.stats.StatsDisplay.lambda$createHomeButtonInStatsScreen$0(StatsDisplay.java:38)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3564)
	at javafx.scene.Scene$ClickGenerator.access$8200(Scene.java:3492)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3860)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
Caused by: java.lang.NullPointerException
	at javafx.scene.image.Image.validateUrl(Image.java:1096)
	at javafx.scene.image.Image.<init>(Image.java:617)
	at net.gazeplay.commons.utils.CustomButton.<init>(CustomButton.java:22)
	at net.gazeplay.ui.scenes.gamemenu.HomeMenuScreen.createExitButton(HomeMenuScreen.java:283)
	at net.gazeplay.ui.scenes.gamemenu.HomeMenuScreen.<init>(HomeMenuScreen.java:68)
	at net.gazeplay.ui.scenes.gamemenu.HomeMenuScreenFactoryBean.getObject(HomeMenuScreenFactoryBean.java:30)
	at net.gazeplay.ui.scenes.gamemenu.HomeMenuScreenFactoryBean.getObject(HomeMenuScreenFactoryBean.java:12)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	... 41 more
```

**Comment by kuhlkrein** [comment]
CustomButton exitButton = new **CustomButton**("data/common/images/power-off.png");
->  ImagePattern value = new ImagePattern(new **Image**(imageResourceLocation), 0, 0, 1, 1, true);
-->  this(**validateUrl**(url), null, 0, 0, false, false, false);

@throws NullPointerException if URL is null 

But obviously url should be equal to "data/common/images/power-off.png" ...

**Comment by Tohaker** [comment]
I have a feeling this may have been caused by `Image` not being able to find the resource, strings don't just become `null` at random. Since resources are now on the classpath, I think this may be fixed. Worth a check.
