### ISSUE TITLE
Space game: error

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/GazePlay#985]
```
2020-01-03 15:17:07,944 ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
2020-01-03 15:17:07,944 ERROR java.lang.Throwable - 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
2020-01-03 15:17:07,945 ERROR java.lang.Throwable - 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
2020-01-03 15:17:07,945 ERROR java.lang.Throwable - 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
2020-01-03 15:17:07,945 ERROR java.lang.Throwable - 	at java.base/java.util.Objects.checkIndex(Objects.java:372)
2020-01-03 15:17:07,945 ERROR java.lang.Throwable - 	at java.base/java.util.ArrayList.remove(ArrayList.java:535)
2020-01-03 15:17:07,945 ERROR java.lang.Throwable - 	at com.sun.javafx.collections.ObservableListWrapper.doRemove(ObservableListWrapper.java:116)
2020-01-03 15:17:07,945 ERROR java.lang.Throwable - 	at javafx.collections.ModifiableObservableListBase.remove(ModifiableObservableListBase.java:179)
2020-01-03 15:17:07,946 ERROR java.lang.Throwable - 	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:332)
2020-01-03 15:17:07,946 ERROR java.lang.Throwable - 	at com.sun.javafx.collections.VetoableListDecorator.remove(VetoableListDecorator.java:221)
2020-01-03 15:17:07,946 ERROR java.lang.Throwable - 	at net.gazeplay.games.space.SpaceGame.lambda$handle$4(SpaceGame.java:419)
2020-01-03 15:17:07,946 ERROR java.lang.Throwable - 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
2020-01-03 15:17:07,946 ERROR java.lang.Throwable - 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
2020-01-03 15:17:07,946 ERROR java.lang.Throwable - 	at javafx.beans.binding.BooleanBinding.invalidate(BooleanBinding.java:174)
2020-01-03 15:17:07,947 ERROR java.lang.Throwable - 	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
2020-01-03 15:17:07,947 ERROR java.lang.Throwable - 	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
2020-01-03 15:17:07,947 ERROR java.lang.Throwable - 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
2020-01-03 15:17:07,947 ERROR java.lang.Throwable - 	at javafx.scene.Node$LazyBoundsProperty.invalidate(Node.java:9774)
2020-01-03 15:17:07,947 ERROR java.lang.Throwable - 	at javafx.scene.Node$MiscProperties.invalidateBoundsInParent(Node.java:6823)
2020-01-03 15:17:07,947 ERROR java.lang.Throwable - 	at javafx.scene.Node.invalidateBoundsInParent(Node.java:3422)
2020-01-03 15:17:07,947 ERROR java.lang.Throwable - 	at javafx.scene.Node.transformedBoundsChanged(Node.java:4045)
2020-01-03 15:17:07,948 ERROR java.lang.Throwable - 	at javafx.scene.Node.doTransformsChanged(Node.java:4992)
2020-01-03 15:17:07,948 ERROR java.lang.Throwable - 	at javafx.scene.Node.access$400(Node.java:398)
2020-01-03 15:17:07,948 ERROR java.lang.Throwable - 	at javafx.scene.Node$1.doTransformsChanged(Node.java:444)
2020-01-03 15:17:07,948 ERROR java.lang.Throwable - 	at com.sun.javafx.scene.NodeHelper.transformsChangedImpl(NodeHelper.java:170)
2020-01-03 15:17:07,948 ERROR java.lang.Throwable - 	at com.sun.javafx.scene.NodeHelper.transformsChanged(NodeHelper.java:119)
2020-01-03 15:17:07,948 ERROR java.lang.Throwable - 	at javafx.scene.Node$NodeTransformation$3.invalidated(Node.java:6122)
2020-01-03 15:17:07,948 ERROR java.lang.Throwable - 	at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:113)
2020-01-03 15:17:07,948 ERROR java.lang.Throwable - 	at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:148)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at javafx.css.StyleableDoubleProperty.set(StyleableDoubleProperty.java:82)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at javafx.scene.Node.setTranslateY(Node.java:5560)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at javafx.animation.TranslateTransition.interpolate(TranslateTransition.java:498)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at javafx.animation.Transition.doPlayTo(Transition.java:218)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:99)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at javafx.animation.Animation.doTimePulse(Animation.java:1101)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
2020-01-03 15:17:07,949 ERROR java.lang.Throwable - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at javafx.animation.Animation$1.timePulse(Animation.java:185)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:515)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
2020-01-03 15:17:07,950 ERROR java.lang.Throwable - 	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
2020-01-03 15:17:07,951 ERROR java.lang.Throwable - 	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
2020-01-03 15:17:07,951 ERROR java.lang.Throwable - 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-03 15:17:11,877 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 1 in ImageLibrary
2020-01-03 15:17:11,878 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 2 in ImageLibrary
2020-01-03 15:17:11,878 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 4 in ImageLibrary
2020-01-03 15:17:11,878 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 1 in ImageLibrary
2020-01-03 15:17:11,878 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 4 in ImageLibrary
2020-01-03 15:17:11,878 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 2 in ImageLibrary
2020-01-03 15:17:11,879 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 0 in ImageLibrary
2020-01-03 15:17:11,879 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 0 in ImageLibrary
2020-01-03 15:17:11,879 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 3 in ImageLibrary
2020-01-03 15:17:11,880 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 2 in ImageLibrary
2020-01-03 15:17:11,880 DEBUG net.gazeplay.commons.utils.games.AbstractImageLibrary - Picking Image at random index 3 in ImageLibrary
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Children: duplicate children added: parent = Group@60b24998
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at javafx.scene.Parent$3.onProposedChange(Parent.java:558)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at net.gazeplay.games.space.SpaceGame.handle(SpaceGame.java:359)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:57)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:515)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
2020-01-03 15:17:15,412 ERROR java.lang.Throwable - 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by schwabdidier** [comment]
When does it occur ?

**Comment by kuhlkrein** [comment]
after some time in the game, nothing special happend before
